### ISSUE TITLE
Case Sensitivity

### ISSUE THREAD

**Issue by joelgaeddert** [davegaeddert/google-sheets-us-states#6]
The script doesn't work for abbreviations that aren't capitalized (ex. ks or Ks doesn't convert to Kansas because of the lowercase letters). Other than that, worked well for my situation. Glad I found it--saved me quite a bit of time!

**Comment by RugbyCharger** [comment]
New to GitHub and coding in general. How do I copy this across to Google Sheets please? Thanks

**Comment by tkonya** [comment]
I have a pull request in to address this issue, it should deal with any input case-insensitively. I've attached my updated code here as well.

[Code.gs.txt](https://github.com/davegaeddert/google-sheets-us-states/files/2080951/Code.gs.txt)

**Comment by davegaeddert** [comment]
Closed by #8
